'''

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

'''

def main():
	final_list = fib_even_sum(1, 2, 2)
	print final_list

def fib_even_sum(a, b, s):
	a, b = b, a + b
	if b % 2 == 0:
		s += b
	if s > 4e6:
		return s
	else:
		return fib_even_sum(a, b, s)

if __name__ == '__main__':
	import boilerplate, time, resource
	t = time.time()
	r = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
	boilerplate.all(main(), t, r)
