'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

import math

def tri_number(n):
	return int(n*(n+1)/2.0)

def is_pentagonal(n):
    x = (math.sqrt(1 + 24 * n) + 1.0)/6.0
    return (x == int(x))

def main():
	for i in range(286,200000):
		x = tri_number(i)
		if is_pentagonal(x):
			#print 'tri #', i, 'val:', x
			return i

if __name__ == '__main__':
	import boilerplate, time
	boilerplate.all(time.time(),main())



